### ISSUE TITLE
register.py doesn't work in Python 2

### ISSUE THREAD

**Issue by 0atman** [alphagov/gds-pre-commit#34]
```shell
Enter your github username:0atman
Performing GitHub OAuth
This creates a personal access token with read:user and read:org scopes. 
Please enter your GitHub 2FA code:
Requesting authorization from GitHub - You will be prompted for your GitHub password.
Enter host password for user '0atman':
Traceback (most recent call last):
  File "./install.py", line 43, in <module>
    register("test")  # Remove test mode argument for production
  File "/code/register.py", line 66, in register
    except json.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

Looks like in Python 2, json decoding errors were `ValueError`s.

**Comment by 0atman** [comment]
Maybe we should warn that the register script needs python3?

**Comment by 0atman** [comment]
Wontfix, upstream bug
